### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by zejnir** [31d4r/SageSay#1]
Your code looks well-organized and readable overall, but I'll provide some suggestions to enhance its clarity, maintainability, and efficiency:

1. You can use lazy initialization for your UI components to improve memory efficiency. This way, the components are only created when they are accessed.
2. Consider marking functions and properties as private if they are not accessed outside the class. This helps encapsulate the implementation details and makes your code more maintainable.
3. The getQuotes function is responsible for fetching quotes and updating the UI. Consider separating these concerns.
4. You might want to handle errors and success scenarios separately in your scheduleQuoteNotification function.
5. Be cautious with force unwrapping, especially when dealing with user settings. Consider using optional binding (if let or guard let) to safely unwrap optionals.
6. Avoid magic numbers in your code. Replace magic numbers with constants or variables with descriptive names.
7. Consider injecting the view model rather than instantiating it directly in your view controller. This promotes better dependency management and testability.
8. Implement proper error handling for network requests and notifications. This will help you identify and handle issues more effectively.

Also, I hope there is documentation for this project, because I can’t see any comments. I hope you will appreciate this suggestions.

**Comment by 31d4r** [comment]
When Flutter dev wants to review Swift code using ChatGPT 😂 But at the end thank you
